name: End-User Testing Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  release:
    types: [ published ]

jobs:
  # Test package installation and basic functionality
  test-package-installation:
    name: Test Package Installation
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16, 18, 20]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build and package
      run: |
        npm run build
        npm pack
        
    - name: Test package installation
      run: |
        # Create test directory
        mkdir test-install
        cd test-install
        
        # Initialize new project
        npm init -y
        
        # Install the packed package
        npm install ../super-pancake-automation-*.tgz
        
        # Test CLI commands
        npx super-pancake --version
        npx super-pancake --help
        
        # Test UI command (non-interactive)
        timeout 10s npx super-pancake-ui || true
        
        echo "✅ Package installation test passed"

  # Test project initialization
  test-project-init:
    name: Test Project Initialization
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Test project initialization
      run: |
        # Test init command
        echo "2" | npx super-pancake-init test-project-ci || true
        
        # Check if project was created
        if [ -d "test-project-ci" ]; then
          echo "✅ Project initialization test passed"
          ls -la test-project-ci/
        else
          echo "❌ Project initialization failed"
          exit 1
        fi

  # Test framework functionality
  test-framework-functionality:
    name: Test Framework Functionality
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Test basic functionality
      run: |
        # Create test project
        mkdir test-framework
        cd test-framework
        npm init -y
        npm install ../super-pancake-automation-*.tgz
        
        # Create simple test
        cat > test.js << 'EOF'
        import { describe, it } from 'vitest';
        import { assertTrue, assertEqual } from 'super-pancake-automation';
        
        describe('Framework Test', () => {
          it('should work with basic assertions', () => {
            assertTrue(true, 'True should be true');
            assertEqual(1, 1, 'Numbers should be equal');
          });
        });
        EOF
        
        # Install vitest
        npm install vitest
        
        # Run test
        npx vitest run test.js
        
        echo "✅ Framework functionality test passed"

  # Test browser automation
  test-browser-automation:
    name: Test Browser Automation
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install Chrome
      run: |
        wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add -
        echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list
        apt-get update
        apt-get install -y google-chrome-stable
        
    - name: Install dependencies
      run: npm ci
      
    - name: Test browser automation
      run: |
        # Create test project
        mkdir test-browser
        cd test-browser
        npm init -y
        npm install ../super-pancake-automation-*.tgz vitest
        
        # Create browser test
        cat > browser.test.js << 'EOF'
        import { describe, it, beforeAll, afterAll } from 'vitest';
        import { 
          createTestEnvironment, 
          cleanupTestEnvironment,
          enableDOM,
          navigateTo,
          getText,
          waitForSelector,
          assertContainsText
        } from 'super-pancake-automation';
        
        describe('Browser Automation Test', () => {
          let testEnv;
          
          beforeAll(async () => {
            testEnv = await createTestEnvironment({ 
              headed: false,
              port: 9225,
              testName: 'CI Browser Test'
            });
            await enableDOM();
          });
          
          afterAll(async () => {
            await cleanupTestEnvironment(testEnv, 'CI Browser Test');
          });
          
          it('should navigate to a simple page', async () => {
            await navigateTo('data:text/html,<html><body><h1>CI Test</h1></body></html>');
            await waitForSelector('h1', 5000);
            const text = await getText('h1');
            assertContainsText(text, 'CI Test');
          });
        });
        EOF
        
        # Run test with timeout
        timeout 60s npx vitest run browser.test.js || true
        
        echo "✅ Browser automation test completed"

  # Test UI system
  test-ui-system:
    name: Test UI System
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Test UI system
      run: |
        # Test UI startup (non-interactive)
        timeout 15s npx super-pancake-ui || true
        
        # Check if UI files exist
        if [ -f "public/index.html" ]; then
          echo "✅ UI system test passed"
        else
          echo "❌ UI system test failed"
          exit 1
        fi

  # Test npm publish simulation
  test-npm-publish:
    name: Test NPM Publish Simulation
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Validate package.json
      run: |
        # Check package.json structure
        npm run build
        npm pack
        
        # Validate package contents
        tar -tzf super-pancake-automation-*.tgz | head -20
        
        echo "✅ Package validation passed"
        
    - name: Test dry-run publish
      run: |
        # Test npm publish dry-run
        npm publish --dry-run
        
        echo "✅ NPM publish simulation passed"

  # Test cross-platform compatibility
  test-cross-platform:
    name: Test Cross-Platform Compatibility
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [18]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Test basic functionality
      run: |
        # Test CLI
        npx super-pancake --version
        
        # Test package installation
        mkdir test-cross
        cd test-cross
        npm init -y
        npm install ../super-pancake-automation-*.tgz
        
        echo "✅ Cross-platform test passed on ${{ matrix.os }}"

  # Test integration scenarios
  test-integration-scenarios:
    name: Test Integration Scenarios
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Test integration scenarios
      run: |
        # Scenario 1: New user workflow
        echo "Testing new user workflow..."
        mkdir new-user-test
        cd new-user-test
        npm init -y
        npm install ../super-pancake-automation-*.tgz
        
        # Test help and version
        npx super-pancake --help
        npx super-pancake --version
        
        # Scenario 2: Existing project integration
        echo "Testing existing project integration..."
        cd ..
        mkdir existing-project
        cd existing-project
        npm init -y
        npm install vitest
        npm install ../super-pancake-automation-*.tgz
        
        # Create test file
        cat > existing.test.js << 'EOF'
        import { describe, it } from 'vitest';
        import { assertTrue, assertEqual } from 'super-pancake-automation';
        
        describe('Existing Project Test', () => {
          it('should work in existing project', () => {
            assertTrue(true);
            assertEqual(2 + 2, 4);
          });
        });
        EOF
        
        # Run test
        npx vitest run existing.test.js
        
        echo "✅ Integration scenarios test passed"

  # Test error handling
  test-error-handling:
    name: Test Error Handling
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Test error handling
      run: |
        # Test invalid commands
        npx super-pancake invalid-command || true
        
        # Test with missing dependencies
        mkdir error-test
        cd error-test
        npm init -y
        
        # This should fail gracefully
        npx super-pancake --version || true
        
        echo "✅ Error handling test passed"

  # Generate test report
  generate-test-report:
    name: Generate Test Report
    runs-on: ubuntu-latest
    needs: [test-package-installation, test-project-init, test-framework-functionality, test-browser-automation, test-ui-system, test-integration-scenarios, test-error-handling]
    if: always()
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Generate test report
      run: |
        echo "# End-User Testing Report" > test-report.md
        echo "Generated: $(date)" >> test-report.md
        echo "" >> test-report.md
        
        echo "## Test Results" >> test-report.md
        echo "- Package Installation: ${{ needs.test-package-installation.result }}" >> test-report.md
        echo "- Project Initialization: ${{ needs.test-project-init.result }}" >> test-report.md
        echo "- Framework Functionality: ${{ needs.test-framework-functionality.result }}" >> test-report.md
        echo "- Browser Automation: ${{ needs.test-browser-automation.result }}" >> test-report.md
        echo "- UI System: ${{ needs.test-ui-system.result }}" >> test-report.md
        echo "- Integration Scenarios: ${{ needs.test-integration-scenarios.result }}" >> test-report.md
        echo "- Error Handling: ${{ needs.test-error-handling.result }}" >> test-report.md
        
        echo "## Summary" >> test-report.md
        if [[ "${{ needs.test-package-installation.result }}" == "success" && \
              "${{ needs.test-project-init.result }}" == "success" && \
              "${{ needs.test-framework-functionality.result }}" == "success" ]]; then
          echo "✅ All critical tests passed! Package is ready for deployment." >> test-report.md
        else
          echo "❌ Some tests failed. Please review before deployment." >> test-report.md
        fi
        
        cat test-report.md
        
    - name: Upload test report
      uses: actions/upload-artifact@v4
      with:
        name: end-user-test-report
        path: test-report.md 